<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \Application\Entity\User implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'userType', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'firstName', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'lastName', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'email', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'street', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'city', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'state', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'zipCode', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'dateTimeLastLogin', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'dateTimeCreated', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'dateTimeModified', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'lockedFlag', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'deletedFlag', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'currentEmployer', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'userAuthentications', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'jobSeeker'];
        }

        return ['__isInitialized__', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'userType', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'firstName', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'lastName', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'email', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'street', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'city', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'state', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'zipCode', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'dateTimeLastLogin', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'dateTimeCreated', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'dateTimeModified', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'lockedFlag', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'deletedFlag', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'currentEmployer', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'userAuthentications', '' . "\0" . 'Application\\Entity\\User' . "\0" . 'jobSeeker'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (User $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserType', []);

        return parent::getUserType();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserType($userType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserType', [$userType]);

        return parent::setUserType($userType);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstName', []);

        return parent::getFirstName();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstName($firstName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstName', [$firstName]);

        return parent::setFirstName($firstName);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastName', []);

        return parent::getLastName();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastName($lastName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastName', [$lastName]);

        return parent::setLastName($lastName);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getStreet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStreet', []);

        return parent::getStreet();
    }

    /**
     * {@inheritDoc}
     */
    public function setStreet($street)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStreet', [$street]);

        return parent::setStreet($street);
    }

    /**
     * {@inheritDoc}
     */
    public function getCity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCity', []);

        return parent::getCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setCity($city)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCity', [$city]);

        return parent::setCity($city);
    }

    /**
     * {@inheritDoc}
     */
    public function getState()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getState', []);

        return parent::getState();
    }

    /**
     * {@inheritDoc}
     */
    public function setState($state)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setState', [$state]);

        return parent::setState($state);
    }

    /**
     * {@inheritDoc}
     */
    public function getZipCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getZipCode', []);

        return parent::getZipCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setZipCode($zipCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setZipCode', [$zipCode]);

        return parent::setZipCode($zipCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateTimeLastLogin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateTimeLastLogin', []);

        return parent::getDateTimeLastLogin();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateTimeLastLogin($dateTimeLastLogin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateTimeLastLogin', [$dateTimeLastLogin]);

        return parent::setDateTimeLastLogin($dateTimeLastLogin);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateTimeCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateTimeCreated', []);

        return parent::getDateTimeCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateTimeCreated($dateTimeCreated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateTimeCreated', [$dateTimeCreated]);

        return parent::setDateTimeCreated($dateTimeCreated);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateTimeModified()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateTimeModified', []);

        return parent::getDateTimeModified();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateTimeModified($dateTimeModified)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateTimeModified', [$dateTimeModified]);

        return parent::setDateTimeModified($dateTimeModified);
    }

    /**
     * {@inheritDoc}
     */
    public function getLockedFlag()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLockedFlag', []);

        return parent::getLockedFlag();
    }

    /**
     * {@inheritDoc}
     */
    public function setLockedFlag($lockedFlag)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLockedFlag', [$lockedFlag]);

        return parent::setLockedFlag($lockedFlag);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeletedFlag()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeletedFlag', []);

        return parent::getDeletedFlag();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeletedFlag($deletedFlag)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeletedFlag', [$deletedFlag]);

        return parent::setDeletedFlag($deletedFlag);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrentEmployer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrentEmployer', []);

        return parent::getCurrentEmployer();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrentEmployer(\Application\Entity\Employer $currentEmployer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrentEmployer', [$currentEmployer]);

        return parent::setCurrentEmployer($currentEmployer);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserAuthentications()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserAuthentications', []);

        return parent::getUserAuthentications();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserAuthentications(\Application\Entity\UserAuthentication $userAuthentications)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserAuthentications', [$userAuthentications]);

        return parent::setUserAuthentications($userAuthentications);
    }

    /**
     * {@inheritDoc}
     */
    public function getJobSeeker()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJobSeeker', []);

        return parent::getJobSeeker();
    }

    /**
     * {@inheritDoc}
     */
    public function setJobSeeker(\Application\Entity\JobSeeker $jobSeeker)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJobSeeker', [$jobSeeker]);

        return parent::setJobSeeker($jobSeeker);
    }

    /**
     * {@inheritDoc}
     */
    public function getValues()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValues', []);

        return parent::getValues();
    }

    /**
     * {@inheritDoc}
     */
    public function toArray($ignore = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', [$ignore]);

        return parent::toArray($ignore);
    }

}
