<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class JobSeeker extends \Application\Entity\JobSeeker implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\JobSeeker' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\JobSeeker' . "\0" . 'user', '' . "\0" . 'Application\\Entity\\JobSeeker' . "\0" . 'subscriberId', '' . "\0" . 'Application\\Entity\\JobSeeker' . "\0" . 'phoneNo', '' . "\0" . 'Application\\Entity\\JobSeeker' . "\0" . 'industry', '' . "\0" . 'Application\\Entity\\JobSeeker' . "\0" . 'headline', '' . "\0" . 'Application\\Entity\\JobSeeker' . "\0" . 'experience', '' . "\0" . 'Application\\Entity\\JobSeeker' . "\0" . 'education', '' . "\0" . 'Application\\Entity\\JobSeeker' . "\0" . 'desiredSalary', '' . "\0" . 'Application\\Entity\\JobSeeker' . "\0" . 'country', '' . "\0" . 'Application\\Entity\\JobSeeker' . "\0" . 'zipCode', '' . "\0" . 'Application\\Entity\\JobSeeker' . "\0" . 'linkedin', '' . "\0" . 'Application\\Entity\\JobSeeker' . "\0" . 'twitter', '' . "\0" . 'Application\\Entity\\JobSeeker' . "\0" . 'facebook', '' . "\0" . 'Application\\Entity\\JobSeeker' . "\0" . 'companyFindFlag');
        }

        return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\JobSeeker' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\JobSeeker' . "\0" . 'user', '' . "\0" . 'Application\\Entity\\JobSeeker' . "\0" . 'subscriberId', '' . "\0" . 'Application\\Entity\\JobSeeker' . "\0" . 'phoneNo', '' . "\0" . 'Application\\Entity\\JobSeeker' . "\0" . 'industry', '' . "\0" . 'Application\\Entity\\JobSeeker' . "\0" . 'headline', '' . "\0" . 'Application\\Entity\\JobSeeker' . "\0" . 'experience', '' . "\0" . 'Application\\Entity\\JobSeeker' . "\0" . 'education', '' . "\0" . 'Application\\Entity\\JobSeeker' . "\0" . 'desiredSalary', '' . "\0" . 'Application\\Entity\\JobSeeker' . "\0" . 'country', '' . "\0" . 'Application\\Entity\\JobSeeker' . "\0" . 'zipCode', '' . "\0" . 'Application\\Entity\\JobSeeker' . "\0" . 'linkedin', '' . "\0" . 'Application\\Entity\\JobSeeker' . "\0" . 'twitter', '' . "\0" . 'Application\\Entity\\JobSeeker' . "\0" . 'facebook', '' . "\0" . 'Application\\Entity\\JobSeeker' . "\0" . 'companyFindFlag');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (JobSeeker $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', array());

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\Application\Entity\User $user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', array($user));

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubscriberId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubscriberId', array());

        return parent::getSubscriberId();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubscriberId($subscriberId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubscriberId', array($subscriberId));

        return parent::setSubscriberId($subscriberId);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoneNo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoneNo', array());

        return parent::getPhoneNo();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoneNo($phoneNo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoneNo', array($phoneNo));

        return parent::setPhoneNo($phoneNo);
    }

    /**
     * {@inheritDoc}
     */
    public function getIndustry()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIndustry', array());

        return parent::getIndustry();
    }

    /**
     * {@inheritDoc}
     */
    public function setIndustry($industry)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIndustry', array($industry));

        return parent::setIndustry($industry);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeadline()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeadline', array());

        return parent::getHeadline();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeadline($headline)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeadline', array($headline));

        return parent::setHeadline($headline);
    }

    /**
     * {@inheritDoc}
     */
    public function getExperience()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExperience', array());

        return parent::getExperience();
    }

    /**
     * {@inheritDoc}
     */
    public function setExperience($experience)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExperience', array($experience));

        return parent::setExperience($experience);
    }

    /**
     * {@inheritDoc}
     */
    public function getEducation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEducation', array());

        return parent::getEducation();
    }

    /**
     * {@inheritDoc}
     */
    public function setEducation($education)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEducation', array($education));

        return parent::setEducation($education);
    }

    /**
     * {@inheritDoc}
     */
    public function getDesiredSalary()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDesiredSalary', array());

        return parent::getDesiredSalary();
    }

    /**
     * {@inheritDoc}
     */
    public function setDesiredSalary($desiredSalary)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDesiredSalary', array($desiredSalary));

        return parent::setDesiredSalary($desiredSalary);
    }

    /**
     * {@inheritDoc}
     */
    public function getCountry()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountry', array());

        return parent::getCountry();
    }

    /**
     * {@inheritDoc}
     */
    public function setCountry($country)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCountry', array($country));

        return parent::setCountry($country);
    }

    /**
     * {@inheritDoc}
     */
    public function getZipCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getZipCode', array());

        return parent::getZipCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setZipCode($zipCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setZipCode', array($zipCode));

        return parent::setZipCode($zipCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getLinkedin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLinkedin', array());

        return parent::getLinkedin();
    }

    /**
     * {@inheritDoc}
     */
    public function setLinkedin($linkedin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLinkedin', array($linkedin));

        return parent::setLinkedin($linkedin);
    }

    /**
     * {@inheritDoc}
     */
    public function getTwitter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTwitter', array());

        return parent::getTwitter();
    }

    /**
     * {@inheritDoc}
     */
    public function setTwitter($twitter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTwitter', array($twitter));

        return parent::setTwitter($twitter);
    }

    /**
     * {@inheritDoc}
     */
    public function getFacebook()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFacebook', array());

        return parent::getFacebook();
    }

    /**
     * {@inheritDoc}
     */
    public function setFacebook($facebook)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFacebook', array($facebook));

        return parent::setFacebook($facebook);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanyFindFlag()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyFindFlag', array());

        return parent::getCompanyFindFlag();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompanyFindFlag($companyFindFlag)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompanyFindFlag', array($companyFindFlag));

        return parent::setCompanyFindFlag($companyFindFlag);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray($ignore = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array($ignore));

        return parent::toArray($ignore);
    }

}
