<div id="message-box" class="alert" style="display:none;margin-top: 10px;">
  <a href="#" class="close">&times;</a>
  <div class="message-content"></div>
</div>

 <div class="login clearfix" ng-app="validationApp" ng-controller="mainController">
    <div class="col-sm-5 bordered">
      <h2 class="blue">Create Free Account</h2>
      <div class="m20">
        <form id="login" name="userForm" ng-submit="submitForm()" novalidate>
          <div class="form-group text-left" ng-class="{ 'has-error' : userForm.name.$invalid && !userForm.name.$pristine }">
          	  <label>Enter Your Basic Info:</label>
              <input type="text" name="name" class="input-sm form-control" placeholder="Your Name"  ng-model="user.name" required />
              <p ng-show="userForm.name.$invalid && !userForm.name.$pristine" class="help-block">You name is required.</p>
            </div>
            <div class="form-group" ng-class="{ 'has-error' : userForm.email.$invalid && !userForm.email.$pristine }">
              <input type="email" class="input-sm form-control" placeholder="Your email address" name="email" ng-model="user.email" required/>
              <p ng-show="userForm.email.$invalid && !userForm.email.$pristine" class="help-block">Enter a valid email.</p>
            </div>
            <br />
             <div class="form-group text-left">
          	  <label>Create Job Alert: <small>(Recommended)</small></label>
              <p class="gray">Get the Freshest jobs in your inbox every day.</p>
              <input type="text" name="title" class="input-sm form-control" placeholder="Job Title or Keyword" />
            </div>
            <div class="form-group">
              <input type="text" name="location" class="input-sm form-control" placeholder="City, State or Zip" />
            </div>
            <br />
          <div class="form-group">
              <input type="submit" value="Create Account" class="btn btn-primary btn-block" ng-disabled="userForm.$invalid"/>
          </div>
          <p class="m40 small">By clicking the button above, I agree to the Resumes 2 Work <br /><a href="<?php echo $this->basePath() . '/terms'; ?>">Terms of Use</a> and <a href="<?php echo $this->basePath() . '/privacy'; ?>">Privacy Policy</a></p>
        </form>
      </div>
    </div>
    <div class="col-sm-offset-1 col-sm-5 regSocial">
    	<h3 class="blue mt0">Join the millions of job seekers finding jobs on Resumes 2 Work! </h3>
            <ul class="features clearfix">
            	<li>Get daily job alerts via email</li>
                <li>Mobile optimized job search tools</li>
                <li>InstaMatch to jobs hiring now</li>
                <li>No spam or banners, just jobs</li>
                <li>One-click apply to jobs</li>
                <li>Best of all, it's FREE!</li>
            </ul>
            <div align="center" class="mb20">
            	<img src="<?php echo $this->basePath(); ?>/images/rapidssl90x90.jpg" alt="sslcert" />
            </div>
            <hr class="blue" />
    	<h4 class="text-center" style="display:none;" >Sign Up with your Social Accounts</h4>
        <div class="text-center" style="display:none;" >
        	<a href="#" class="reg gp"><img src="<?php echo $this->basePath(); ?>/images/Gplus.jpg" alt="GP" />Sign up with Google</a>
            <a href="#" class="reg fb"><img src="<?php echo $this->basePath(); ?>/images/facebook.jpg" alt="GP" />Sign up with Facebook</a>
            <a href="#" class="reg in"><img src="<?php echo $this->basePath(); ?>/images/linked-in.jpg" alt="GP" />Sign up with Linked In</a>
        </div>
        
    </div>
    </div>
    <script>
 // create angular app
	var validationApp = angular.module('validationApp', []);

	// create angular controller
	validationApp.controller('mainController', function($scope,$http) {
		$('.register-link').hide();
		// function to submit the form after all validation has occurred			
		$scope.submitForm = function() {

			// check to make sure the form is completely valid
			if ($scope.userForm.$valid) {
				var formData = {
					      'name' : document.userForm.name.value,
					      'email' : document.userForm.email.value,
					      'title' : document.userForm.title.value,
					      'location' : document.userForm.location.value,
					      'provider': "EMAIL"
					     
					    };
			        $http.post('/api/register', formData).success(function(response){
			        	console.log(response.message);
			        	if(response.message){
				        	if(response.status=="Successful"){
				        		$('#message-box').removeClass('alert-danger');
				        		$('#message-box').addClass('alert-success');
				        		$('#message-box .message-content').html('Thank you for registering with Resumes2Work. You will receive an email shortly with instruction to setup your password. <a class="btn btn-primary" title="" href="/">Login</a>');
				        		$('.login').hide(); 
				        		
				        	}else{
				        		$('#message-box').removeClass('alert-success');
				        		$('#message-box').addClass('alert-danger');
				        		$('#message-box .message-content').html(response.message);
				        	}
				        	$("#message-box").show();
			        		
			        		$(".close").click(function(){
			        			$("#message-box").hide();
			        		});
			        	}
			        	
				        /*success callback*/
				        });
				//alert('our form is amazing');
			}

		};

	});

    </script>