<?php if($this->status=='GetResetToken'){?>
<style>
		.statusMsg{
			color: red;
			text-align: center;
		}
    </style>
    
	
 <div class="center forgot bordered">
      <h1>Reset Password</h1>
      <div class="row m40">
      <div class="col-sm-offset-1 col-sm-10">
        <form class="form-horizontal" id="forgot" method="post">
            <div class="form-group">
                <p class="text-left">Create a new password for your <strong><?php echo $this->data->getUserName();?></strong> account below.</p>
            </div>
          <div class="form-group">
              <input name="password" id="password" type="password" class="input-sm form-control" placeholder="Enter new password" />
            </div>
            <div class="form-group">
              <input name="confirmPassword" id="confirmPassword" type="password" class="input-sm form-control" placeholder="Confirm password" />
			</div>
          <div class="form-group">
              <input type="submit" id="submitBtn"  value="Save Password" class="btn btn-primary btn-block" />
          </div>
          <input type="hidden" name="resetToken" value="<?php echo $this->data->getResetToken();?>">
           <input type="hidden" id="username" name="username" value="<?php echo $this->data->getUserName();?>">
          <input type="hidden" name="id" value="<?php echo $this->data->getUser()->getId();?>">
        </form>
        </div>
      </div>
    </div>
    <?php }else if($this->status=='InvalidToken'){?>
    <div class="center">
	   <div class="alert alert-danger">
		  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
		  <strong>Invalid token!</strong> 
		</div>
	</div>
    <?php }else if($this->status=='PasswordChanged'){?>
    <div class="center">
		<div class="alert alert-success">
		  <strong>Password set successfully!</strong> To login <a href="<?php echo $this->basePath();?>/login">click here</a>
		</div>
		<meta http-equiv="refresh" content="2; url=/login" />
	</div>
  <?php }else if($this->status=='PasswordChangeFailed'){?>
    <div class="center">
	   <div class="alert alert-danger">
		  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
		  <strong>Password set failed!</strong> 
		</div>
	</div>
    <?php }?>
