<?php $user =$this->getHelperPluginManager()->getServiceLocator()->get('AuthService')->getIdentity();?>
<div ng-app="Resume2WorkApp" ng-controller="ProfileController">
    <div class="grayBg">
    <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <form class="form-horizontal search" name="searchForm" id="searchForm" action="/search" method="GET">
          <div class="form-group">
            <div class="col-sm-3">
              <input type="text" name="term" class="form-control input-sm" placeholder="Job Title/Keyword" />
            </div>
            <div class="col-sm-3">
              <input type="text" name="location" class="form-control  input-sm" placeholder="Location(City, State, Zip)" />
            </div>
            <div class="col-sm-3">
            <button type="submit" class="btn btn-primary btn-sm">Search Jobs</button>
            </div>
          </div>
        </form>
      </div>
    </div>
    </div>
    </div>
    <div class="container">
    <div class="content">
      <div class="row">
        <div class="col-sm-9">
          <h2>My Profile</h2>
          <p>When you apply to jobs through Resumes 2 Work, this information is visible to these employers and it is what they will use to contact you.</p>
          <div class="boxed profile-pic">
            <div class="circle"> <img src="images/profile-img.jpg" alt="sarah"/> <a href="#">Change</a> </div>
            <p>Profile Photo</p>
            <h3 class="blue"></h3>
            <a class="blue" id="name" data-type="text" data-pk="1" data-name="name" data-url="/api/profile"><?php echo $user->getFirstName().' '.$user->getLastName();?></a>
          </div>
          <div class="boxed">
          <div ng-if="changePasswordError!=null" class="alert alert-danger has-error">
          	<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				  <div class="message-content"> {{ changePasswordError }}</div>
		  </div>
		  <div ng-if="changePasswordSuccess!=null" class="alert alert alert-success">
		  	<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				  <div class="message-content"> {{ changePasswordSuccess }}</div>
		  </div>
		  <div ng-if="aboutMeError!=null" class="alert alert-danger has-error">
          	<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				  <div class="message-content"> {{ aboutMeError }}</div>
		  </div>
		  <div ng-if="aboutMeSuccess!=null" class="alert alert alert-success">
		  	<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				  <div class="message-content"> {{ aboutMeSuccess }}</div>
		  </div>
            <div class="col-sm-12 ptb20">
              <!-- tabs left -->
              <div class="tabbable">
                <ul class="nav nav-pills nav-stacked col-md-3">
                  <li  class="active"><a href="#a" data-toggle="tab">About Me</a></li>
                  <li><a href="#b" data-toggle="tab">Change Password</a></li>
                </ul>
                <div class="tab-content col-md-9">
                  <div class="tab-pane active" id="a">
                        <div class="col-sm-12">
                          <form name="aboutMeForm" id="aboutMeForm" role="form" ng-submit="submitAboutMeForm()" novalidate>    
                            <div class="form-group">
                              <label for="inputEmail1" class="required">Email Address</label>  
                              <span id="LinkPhoneNo"></span>                            
                              <input type="email" class="form-control" disabled="disabled" id="inputEmail1" value="<?php echo $user->getEmail();?>" />
                            </div>                                                        
                            <div class="form-group">
                              <span id="LinkIndustry"></span>
                              <label for="inputPhone">Phone Number</label>
                              <input type="text" class="form-control" ng-init="user.phone='<?php echo $profileData->getPhoneNo();?>'" id="inputPhone" ng-model="user.phone" />
                            </div>
                            <div class="form-group">
                              <span id="LinkHeadline"></span>
                              <label for="inputIndus">Industry</label>
                              <select class="form-control" id="inputIndus" ng-model="user.industry" ng-init="user.industry='<?php echo $profileData->getIndustry();?>'">
                                <?php foreach($industryList as $key=>$value){?>
                                <option value="<?php echo $key;?>"><?php echo $value;?></option>
                                <?php }?>
                              </select>
                            </div>
                            <div class="form-group">
                              <span id="LinkExperience"></span>
                              <label for="inputTitle">Your professional headline</label>
                              <input type="text" class="form-control" id="inputTitle" ng-model="user.headline" ng-init="user.headline='<?php echo $profileData->getHeadline();?>'"/>
                            </div>
                            <div class="form-group">
                              <span id="LinkEducation"></span>
                              <label for="inputExp">Experience</label>
                              <select class="form-control" id="inputExp" ng-model="user.experience" ng-init="user.experience='<?php echo $profileData->getExperience();?>'">
                                <?php foreach($experienceList as $key=>$value){?>
                                <option value="<?php echo $key;?>"><?php echo $value;?></option>
                                <?php }?>
                              </select>
                            </div>
                            <div class="form-group">
                              <span id="LinkDesiredsalary"></span>
                              <label for="inputEdu">Education</label>
                              <select class="form-control" id="inputEdu" ng-model="user.education" ng-init="user.education='<?php echo $profileData->getEducation();?>'">
                                <?php foreach($educationList as $key=>$value){?>
                                <option value="<?php echo $key;?>"><?php echo $value;?></option>
                                <?php }?>
                              </select>
                            </div>
                            <div class="form-group">
                              <span id="LinkLocation"></span>
                              <label for="inputSal">Desired Salary</label>
                              <select class="form-control" id="inputSal" ng-model="user.desired_salary" ng-init="user.desired_salary='<?php echo $profileData->getDesiredSalary();?>'">
                                <?php foreach($salaryList as $key=>$value){?>
                                <option value="<?php echo $key;?>"><?php echo $value;?></option>
                                <?php }?>
                              </select>
                            </div>
                            <div class="form-group">
                              <label for="inputCountry">Country</label>
                              <select class="form-control" id="inputCountry" ng-model="user.country" ng-init="user.country='<?php echo $profileData->getCountry();?>'">
                                <?php foreach($countryList as $key=>$value){?>
                                <option value="<?php echo $key;?>"><?php echo $value;?></option>
                                <?php }?>
                              </select>
                            </div>
                            <div class="form-group">                              
                              <label for="inputZip">Zip Code</label>
                              <input type="text" class="form-control" id="inputZip" ng-model="user.zip_code" ng-init="user.zip_code='<?php echo $profileData->getZipCode();?>'"/>
                            </div>
                            <span id="LinkSocialurl"></span>
                            <div class="form-group">
                              <label for="inputIN">LinkedIn URL</label>
                              <input type="text" class="form-control" id="inputIN" ng-model="user.linkedin" ng-init="user.linkedin='<?php echo $profileData->getLinkedin();?>'"/>
                            </div>
                            <div class="form-group">
                              <label for="inputTwit">Twitter URL</label>
                              <input type="text" class="form-control" id="inputTwit" ng-model="user.twitter" ng-init="user.twitter='<?php echo $profileData->getTwitter();?>'"/>
                            </div>
                            <div class="form-group">
                              <label for="inputFB">Facebook URL</label>
                              <input type="text" class="form-control" id="inputFB" ng-model="user.facebook" ng-init="user.facebook='<?php echo $profileData->getFacebook();?>'"/>
                            </div>
                            <div class="checkbox text-center">
                              <label>
                                <input type="checkbox" id="checkCompanyFindFlag" ng-model="user.company_find_flag"  								
								ng-init="user.company_find_flag = '<?php if($profileData->getCompanyFindFlag()==1) {echo '1';}else{echo '0';}?>'" 
																 ng-true-value="'1'" ng-false-value="'0'"  <?php if($profileData->getCompanyFindFlag()==1) {echo 'checked';}else{echo '';}?>
								 >
                                Allow companies to find my resume</label>
                            </div>
                            <button type="submit" class="btn btn-primary btn-block">Save Profile</button>
                          </form>
                        </div>
                  </div>
                  <div class="tab-pane" id="b">
                  	<div class="col-sm-12">
                    	<form name="changePasswordForm" id="changePasswordForm" ng-submit="submitChangePasswordForm()" novalidate>
                    		
                        	<div class="form-group">
                              <label for="inputPsw" class="required">New Password</label>
                              <input type="password" name="password" id="password" ng-model="user.password" class="form-control" />
                            </div>
                            <div class="form-group">
                              <label for="inputCpsw" class="required">Confirm Password</label>
                              <input type="password" name="confirmPassword" id="confirmPassword" class="form-control" ng-model="user.confirmPassword" ng-change="checkPassword()" required />
                              <p ng-show="invalidPassword==true" class="help-block">Password doesn't match. <br/>- OR - <br/> Password length is less than 8 charactors </p>
                            </div>
                            <div class="checkbox text-center">
                              <label>
                                <input type="checkbox" onchange="document.getElementById('password').type = this.checked ? 'text' : 'password';document.getElementById('confirmPassword').type = this.checked ? 'text' : 'password' "> Show password
								</label>
                            </div>
                            <button type="submit" class="btn btn-primary btn-block" ng-disabled="changePasswordForm.$invalid">Save Password</button>
                          </form>
                          <div class="alert alert-warning mt20">
                          		<h4>Security Instruction</h4>
                                <p>To help ensure the security of your personal information, please choose a password that is atleast 8 characters long.</p>
                          </div>
                    </div>
                  </div>
                </div>
              </div>
              <!-- /tabs --> </div>
          </div>
          <!-- /row --> <div class="clear"></div>
        </div>
        
        <div class="col-sm-3">
        	<div class="border-box" style="display:none;">
        	<!-- Profile completeness -->
          <!--  <h4><span aria-hidden="true" class="glyphicon glyphicon-user green"></span> Profile Completeness</h4>
          <div class="progress">
              <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100" style="width: 10%;">
                10%
              </div>
            </div>-->
          <p>Add more information to stand out 
            from the crowd! <small> (optional)</small></p>
          <ul class="plus-bullet">
            <li><a href="#LinkPhoneNo">Add your phone number</a></li>
            <li><a href="#LinkIndustry">Add your industry</a></li>
            <li><a href="#LinkHeadline">Add your headline</a></li>
            <li><a href="#LinkExperience">Add your experience level</a></li>
            <li><a href="#LinkEducation">Add your education level</a></li>
            <li><a href="#LinkDesiredsalary">Add your desired salary</a></li>
            <li><a href="#LinkLocation">Add your location</a></li>
            <li><a href="#LinkSocialurl">Add your social networks</a></li>
          </ul>
          </div>
          <!-- Linkedin import -->
          <!-- <div class="border-box text-center">
          	  <img src="images/linkedIn-logo.jpg" alt="likedin" class="mb20"/>
              <br />
              <button type="button" class="btn btn-primary">Import from Linked In</button>
              <p class="mt20">This will automatically populate your Resumes 2 Work resume on file and profile information. You can refresh them at any time by importing again.</p>
          </div> -->
          <div class="alert alert-warning mt20">
              <h4>Why should I fill out my profile?</h4>
              <p>Having a rich profile will help you stand out from the crowd and give employers more reasons to pay attention to your job application.</p>
              <br />
              <h4>Is my information private?</h4>
              <p>Yes. Your information is not shared with anyone without your explicit consent. If you would like to add yourself to the resume database, so employers can contact you about job opportunities.</p>
          </div>
        </div>
      </div>
    </div>
    </div>
    </div>
<script>
    var app = angular.module('Resume2WorkApp', []);
    app.controller('ProfileController', function ($scope, $http) {
    	$scope.userId = <?php echo $user->getId();?>;     	
        $scope.submitChangePasswordForm = function () {
        	if($scope.user.password == $scope.user.confirmPassword && $scope.user.password.length>=8){
        		$scope.invalidPassword=false; 
        		 var form ={
                         "password": $scope.user.password
                       };
                       $http.post('/api/change-password', form).success(function (response) {
                           if (response.status == "Successful") {
                        	   $scope.changePasswordSuccess = response.message;
                        	   $scope.changePasswordError = null;
                           } else {
                               $scope.changePasswordError = response.message;
                               $scope.changePasswordSuccess = null;                            
                           }
                       });
        		
        	}else{
        		$scope.invalidPassword=true;
        	}
        };
		
        $scope.submitAboutMeForm = function () {
            if($scope.user){
			 
        	var form ={
                    "phone": $scope.user.phone,
                    "industry":$scope.user.industry,
                    "headline":$scope.user.headline,
                    "experience":$scope.user.experience,
                    "education":$scope.user.education,
                    "desired_salary":$scope.user.desired_salary,
                    "country":$scope.user.country,
                    "zip_code":$scope.user.zip_code,
                    "linkedin":$scope.user.linkedin,
                    "twitter":$scope.user.twitter,
                    "facebook":$scope.user.facebook,
                    "company_find_flag":$scope.user.company_find_flag,
                  };
                  $http.post('/api/profile', form).success(function (response) {
                      if (response.status == "Successful") {
                   	   $scope.aboutMeSuccess = response.message;
                   	   $scope.aboutMeError = null;
                      } else {
                          $scope.aboutMeError = response.message;
                          $scope.aboutMeSuccess = null;                            
                      }
                  });
            }
        };
        $scope.checkPassword = function () {
            
        };

    });
    $(document).ready(function() {
        $('#name').editable();
        $('#name').on('save', function(e, params){
            $('#displayName').html(params.newValue);
        });
    });

    

</script>
<link href="/css/bootstrap-editable.css" rel="stylesheet">
<script src="/js/bootstrap-editable.min.js"></script>