<script data-require="ui-bootstrap@*" data-semver="0.12.1" src="https://angular-ui.github.io/bootstrap/ui-bootstrap-tpls-0.12.1.min.js"></script>
<div ng-app="JobAlertApp" ng-controller="JobAlertController">

	<div class="grayBg">
		<div class="container">
			<div class="row">
			  <div class="col-sm-12">
				<form class="form-horizontal search" name="searchForm" id="searchForm" action="/search" method="GET">
				  <div class="form-group">
					<div class="col-sm-3">
					  <input type="text" name="term" class="form-control input-sm" placeholder="Job Title/Keyword" />
					</div>
					<div class="col-sm-3">
					  <input type="text" name="location" class="form-control  input-sm" placeholder="Location(City, State, Zip)" />
					</div>
					<div class="col-sm-3">
					<button type="submit" class="btn btn-primary btn-sm">Search Jobs</button>
					</div>
				  </div>
				</form>
			  </div>
			</div>
		</div>
    </div>
	
	
	<div class="container">
		<div class="content">
			<div class="row">
				<div class="col-lg-10 col-md-9">
					<h3>Job Alert
						<button class="btn btnr2w pull-right" type="button" ng-click="onShowCreate()"><span
								class="glyphicon glyphicon-plus"
								aria-hidden="true"></span> Create Job Alert
						</button>
					</h3>
					<p class="mb20">For each alert you create, you will receive a daily email with jobs matching that
						search and location.&nbsp;&nbsp;Jobs are pulled from hundreds of boards to give you lots of opportunites!</p>
					<div id="message-box" class="alert" style="display:none;margin-top: 10px;">
					  <a href="#" class="close">&times;</a>
					  <div class="message-content"></div>
					</div>
					<div class="boxed listing-boxed">
						<ul class="jobs">
							<li ng-repeat="jobAlert in jobAlerts">
								<div class="item">
									<h4><a href="#" ng-click="searchJobs(jobAlert)"><span class="glyphicon glyphicon-envelope"
														  aria-hidden="true"></span><strong>{{ jobAlert.title }}</strong> Jobs
											within {{ jobAlert.radius }} miles of <strong>{{ jobAlert.location }}</strong></a></h4>
									<button type="button" class="btn btn-default btn-sm" ng-click="searchJobs(jobAlert)"><span
											class="glyphicon glyphicon-share-alt" aria-hidden="true"></span> View Jobs
									</button>
									<button type="button" class="btn btn-default btn-sm" data-toggle="modal"
											data-target="#editJob" ng-click="onShowEdit(jobAlert)"><span class="glyphicon glyphicon-edit"
																		 aria-hidden="true"></span> Edit
									</button>
									<button type="button" class="btn btn-default btn-sm" ng-click="onDelete(jobAlert)"><span
											class="glyphicon glyphicon-trash" aria-hidden="true" ></span> Delete
									</button>
									<!-- Commented toggle button as its descoped -->
									<!-- <div class="checkbox"><input type="checkbox"  id="cb{{jobAlert.id}}" class="switch_onoff" data-checklist-model="jobAlert.enabled" data-checklist-value="jobAlert.enabled" 
										ng-checked="jobAlert.enabled" ng-true-value="'1'" ng-false-value="'0'"  ng-click="onUnSubscribe(jobAlert)" />
										<label for="cb{{jobAlert.id}}" class="switchlabel"></label>
									</div> -->
								</div>
							</li>
						</ul>
						<nav class="text-center">                        
							 <pagination 
				  ng-model="currentPage"
				  total-items="jobAlertsAll.length"
				  max-size="maxSize"
				  class="pagination-sm"
				  items-per-page="numPerPage"  
				  boundary-links="true">
				</pagination>
						</nav>
					</div>
				</div>
				<div class="col-lg-2 col-md-3">
					<div class="ads mt20" style="display:none;">
						advertisement
					</div>
					<div class="profile-progress" style="display:none;">
						<h4><span class="glyphicon glyphicon-user green" aria-hidden="true"></span> Profile Completeness
						</h4>

						<div class="progress">
							<div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="60"
								 aria-valuemin="0" aria-valuemax="100" style="width: 60%;">
								60%
							</div>
						</div>
						<p>Add more inormation to stand out from the crowd!
							<small>[optional]</small>
						</p>
						<a class="btn btn-default" href="#">Edit My Profile</a>
					</div>
				</div>
			</div>
		</div>
		<!--Create job Model-->
		<div class="modal fade" id="jobAlertPopup" tabindex="-1" role="dialog">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
								aria-hidden="true">&times;</span></button>
						<h4 class="modal-title"><span ng-if="jobAlert.action!='edit'">Create</span><span ng-if="jobAlert.action=='edit'">Edit</span> Job Alert</h4>
					</div>
					<div class="modal-body">
						<div class="row">
							<div class="col-sm-7">
								<form class="form-horizontal" ng-model="jobAlert">
									<div class="form-group">
										<div class="col-sm-12">
											<label>Job Title</label>
											<input type="text" class="form-control" placeholer="BI Developer"
												   ng-model="jobAlert.title" required/>
										</div>
									</div>
									<div class="form-group">
										<div class="col-sm-12">
											<label>Location</label>
											<input type="text" class="form-control" placeholer="San Jose, CA"
												   ng-model="jobAlert.location" required/>
										</div>
									</div>
									<div class="form-group">
										<div class="col-sm-12">
											<label>Radius</label>
											<select class="form-control" ng-model="jobAlert.radius" required>
												<option value="10">Within 10 miles</option>
												<option value="15">Within 15 miles</option>
												<option value="20">Within 20 miles</option>
												<option value="25">Within 25 miles</option>
												<option value="30">Within 30 miles</option>
											</select>
										</div>
									</div>
		
									<button ng-show=!jobAlert.action type="button" class="btn btn-primary" ng-click="onCreate()" >Create Job
										Alert
									</button>
									<button ng-show=jobAlert.action type="button" class="btn btn-primary" ng-click="onCreate()"> Edit Job
										Alert
									</button>
									<a href="#" data-dismiss="modal" class="plr10">Cancel</a>
								</form>
							</div>
							<div class="col-sm-5">
								<div class="alert alert-warning" role="alert">
									<strong>Job Alert Tips:</strong>
									<ul class="pl15">
										<li>Enter a job title and be as specific as possible.</li>
										<li>Put a minus sign before any terms you don't want, like: -travel, etc.</li>
										<li>For location, a zip code is generally better than entering city, state.</li>
										<li>Learn more about how to create an effective job alerts</li>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div><!-- /.modal-content -->
			</div><!-- /.modal-dialog -->
		</div><!-- /.Create modal -->
	</div>
</div>
<script>
    var app = angular.module('JobAlertApp', ['ui.bootstrap']);
    app.controller('JobAlertController', function ($scope, $http) {
    	$scope.jobAlerts=[];
    	$scope.currentPage = 1;
		$scope.numPerPage = 5;
		$scope.maxSize = 5;
		$scope.alert_delete_url="/api/job-alert-delete";
		$scope.alert_unsubscribe_url="/api/job-alert-unsubscribe";
		
        $scope.init = function () {

            $http.get("/api/job-alert").success(function (response) {
                if (response.status == "Successful") {
                    
                    $scope.jobAlertsAll = response.result;
                    
                    $scope.$watch('currentPage + numPerPage', function() {
							var begin = (($scope.currentPage - 1) * $scope.numPerPage);
                 	    var end = begin + $scope.numPerPage;
							$scope.jobAlerts = $scope.jobAlertsAll.slice(begin, end);
                	  });
              	  
                }else{
                	$scope.jobAlerts = null;
                }
            });
        };
        $scope.onShowCreate = function () {
            $scope.jobAlert = {radius: "10"};
            $("#jobAlertPopup").modal();
        };

        $scope.onShowEdit = function (jobAlert) {
            $scope.jobAlert = {radius:jobAlert.radius,title:jobAlert.title,location:jobAlert.location, action:"edit", id:jobAlert.id};
            $("#jobAlertPopup").modal();
        };

        $scope.onCreate = function () {
            if ($scope.jobAlert.title != "" && $scope.jobAlert.location != "") {
                var form = {
                    "title": $scope.jobAlert.title,
                    "location": $scope.jobAlert.location,
                    "radius": $scope.jobAlert.radius,
                    "id": $scope.jobAlert.id,
                    "action":$scope.jobAlert.action
                    
                    
                };
                $http.post('/api/job-alert', form).success(function (response) {
                    if (response.status == "Successful") {
                        window.location = "/job-alert";

                        if($scope.jobAlert.action){
	                        $('#message-box').removeClass('alert-danger');
			        		$('#message-box').addClass('alert-success');
			        		$('#message-box .message-content').html('Alert has been Updated Successfully');
                        }
                    } else {
                    	if($scope.jobAlert.action){
	                    	$('#message-box').addClass('alert-danger');
	 		        		$('#message-box').removeClass('alert-success');
	 		        		$('#message-box .message-content').html('Update of Alert Failed');
                    	}else{
							 alert("Failed");
						}
                    }
					$("#message-box").show();
	        		
	        		$(".close").click(function(){
	        			$("#message-box").hide();
	        		});
                });
            }

        };

        $scope.onDelete = function (jobAlert) {
    		var postData ={"jobAlert": jobAlert,};
        		$http.post($scope.alert_delete_url,postData) .success(function (response) {

            		if (response.status == "Successful"){
            			 $scope.jobAlertsAll = response.result;
                         
                         $scope.$watch('currentPage + numPerPage', function() {
     							var begin = (($scope.currentPage - 1) * $scope.numPerPage);
                      	    var end = begin + $scope.numPerPage;
     							$scope.jobAlerts = $scope.jobAlertsAll.slice(begin, end);
                     	  });

                        $('#message-box').removeClass('alert-danger');
			        	$('#message-box').addClass('alert-success');
			        	$('#message-box .message-content').html(jobAlert.title+' Jobs within ' + jobAlert.radius +' milles of ' +jobAlert.location + ' is deleted');
            		}else{
            			 $('#message-box').addClass('alert-danger');
 			        	$('#message-box').removeClass('alert-success');
 			        	$('#message-box .message-content').html('Deletion of ' +jobAlert.title+' Jobs within ' + jobAlert.radius +' milles of ' +jobAlert.location + ' is Failed');
            		}
            		$("#message-box").show();
	        		
	        		$(".close").click(function(){
	        			$("#message-box").hide();
	        		});

            		
        		});             
              }

       	 $scope.onUnSubscribe = function (jobAlert) {
           		var postData ={"jobAlert": jobAlert,};
        		$http.post($scope.alert_unsubscribe_url,postData) .success(function (response) {

            		if (response.status == "Successful"){
            			 $scope.jobAlertsAll = response.result;
                         
                         $scope.$watch('currentPage + numPerPage', function() {
     							var begin = (($scope.currentPage - 1) * $scope.numPerPage);
                      	    var end = begin + $scope.numPerPage;
     							$scope.jobAlerts = $scope.jobAlertsAll.slice(begin, end);
                     	  });
                    $messageStatus = jobAlert.enabled?' Unsubscribed':' Subscribed' ;
                    $('#message-box').removeClass('alert-danger');
			        $('#message-box').addClass('alert-success');
			        $('#message-box .message-content').html(jobAlert.title+' Jobs within ' + jobAlert.radius +' milles of ' +jobAlert.location +  $messageStatus + ' Successfully' );
            		}
            		$("#message-box").show();
	        		
	        		$(".close").click(function(){
	        			$("#message-box").hide();
	        		});

            		
        		});             
              }

        $scope.searchJobs = function (jobAlert) {
            if (jobAlert.title != "" && jobAlert.location != "" && jobAlert.radius != "") {
                $forwardUrl = '/search?term=' + encodeURIComponent(jobAlert.title) + "&location=" + jobAlert.location + "&radius=" + jobAlert.radius
            	window.location = $forwardUrl;
            }

        };

        $scope.init();
    });

</script>