<?php $logoUrl = $this->basePath().'/images/logo.png';?>
<header role="main" id="header">
	<nav class="navbar navbar-inverse navbar-fixed-top" id="main-navbar">
	<div class="container<?php if($this->isHome){echo "-fluid";}?>">
	<div class="navbar-header"> <a href="<?php echo $this->basePath(); ?>/" class="logo"><img src="<?php echo $logoUrl;?>" alt="R2W"/></a> </div>
<?php if($this->isLoggedIn){?>
          <ul class="nav navbar-nav pull-right">
            <li class="dropdown user-menu"><a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Hello <span id="displayName"><?php echo $this->user->getFirstName().' '.$this->user->getLastName();?></span> <span class="caret"></span></a>
            <ul class="dropdown-menu">
                <li><a href="<?php echo $this->basePath(); ?>/profile">My Profile</a></li>
                <li><a href="<?php echo $this->basePath(); ?>/logout">Sign Out</a></li>
              </ul>              
            </li>
            <li>
            	<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#dsMenu" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </button>
            </li>
          </ul>
          <?php if(!$this->isHome){?>
          <div class="collapse navbar-collapse" id="dsMenu">
          <ul class="nav navbar-nav menu">
            <li><a href="<?php echo $this->basePath(); ?>/job-alert"><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> Job Alerts</a></li>
            <li><a href="<?php echo $this->basePath(); ?>/dashboard"><span aria-hidden="true" class="glyphicon glyphicon-home"></span> Dashboard</a></li>
            <li class="visible-mb"><a href="<?php echo $this->basePath(); ?>/profile">My Profile</a></li>
            <li class="visible-mb"><a href="<?php echo $this->basePath(); ?>/logout">Sign Out</a></li>
          </ul>
          </div>
          <?php }?>
          <?php //echo $this->render('menu.phtml');?>

    <?php }else{?>       
          <ul class="nav navbar-nav pull-right">
          	<li class="first register-link"><a href="<?php echo $this->basePath(); ?>/register">Register</a></li>
            <li class="login-link"><a href="<?php echo $this->basePath(); ?>/login">Login</a></li>
          </ul>   
<?php }?>
</div>
</nav>
</header>

