<nav id="slidx_menu">
            <ul>
              <li><a href="<?php echo $this->basePath(); ?>/" class="active">Search</a></li>
              <li><a href="<?php echo $this->basePath(); ?>/dashboard">Dashboard</a></li>
              <li><a href="<?php echo $this->basePath(); ?>/job-alert">Job Alert</a></li>              
              <li><a href="<?php echo $this->basePath(); ?>/profile">My Profile</a></li>
              <li><a href="<?php echo $this->basePath(); ?>/logout">Signout</a></li>
            </ul>
          </nav>