<div class="grayBg">
    <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <form class="form-horizontal search">
          <div class="form-group">
            <div class="col-sm-3">
              <input type="text" class="form-control input-sm" placeholder="Job Title/Keyword" />
            </div>
            <div class="col-sm-3">
              <input type="text" class="form-control  input-sm" placeholder="Location(City, State, Zip)" />
            </div>
            <div class="col-sm-3">
            <button type="submit" class="btn btn-primary btn-sm">Search Jobs</button>
            </div>
          </div>
        </form>
      </div>
    </div>
    </div>
    </div>
     <div class="container">
    <div class="content">
    	<div class="row">
        	<div class="col-sm-12">
            	<h2>Your Recommended Jobs: <small>Monday, December 28, 2015</small></h2>
            </div>
        </div>
      <div class="row joblist">
        <div class="col-sm-6">
          <div class="boxed">
          		<div class="head">
                	<span>CO</span>
                    <a href="#"><h3>Junior Graphic Designer - Full Time</h3></a>
                    <p>CompAndSsave.com-CA Team | Newark, CA</p>
                </div>
                <p>orem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ut luctus urna, eget cursus sapien. Vivamus vitae lobortis mauris, eget tincidunt enim. Donec bibendum, erat vel tincidunt vehicula, ipsum nisl blandit nunc, malesuada laoreet neque sapien eget urna. Donec dapibus, metus eu ultrices consectetur, ipsum est pretium neque, ut sollicitudin lorem quam et neque. Suspendisse ultrices mauris quis erat luctus tristique. Morbi imperdiet, ipsum a bibendum laoreet, nibh leo lacinia mauris, non commodo nisl massa consequat nunc. Proin sollicitudin dictum hendrerit.</p>
                <span class="newJob">new</span>
                <div class="close">X</div>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="boxed">
          		<div class="head">
                	<span>CO</span>
                    <a href="#"><h3>Junior Graphic Designer - Full Time</h3></a>
                    <p>CompAndSsave.com-CA Team | Newark, CA</p>
                </div>
                <p>orem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ut luctus urna, eget cursus sapien. Vivamus vitae lobortis mauris, eget tincidunt enim. Donec bibendum, erat vel tincidunt vehicula, ipsum nisl blandit nunc, malesuada laoreet neque sapien eget urna. Donec dapibus, metus eu ultrices consectetur, ipsum est pretium neque, ut sollicitudin lorem quam et neque. Suspendisse ultrices mauris quis erat luctus tristique. Morbi imperdiet, ipsum a bibendum laoreet, nibh leo lacinia mauris, non commodo nisl massa consequat nunc. Proin sollicitudin dictum hendrerit.</p>
                <div class="close">X</div>
          </div>
        </div>
      </div>
      <div class="row joblist">
        <div class="col-sm-6">
          <div class="boxed">
          		<div class="head">
                	<span>CO</span>
                    <a href="#"><h3>Junior Graphic Designer - Full Time</h3></a>
                    <p>CompAndSsave.com-CA Team | Newark, CA</p>
                </div>
                <p>orem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ut luctus urna, eget cursus sapien. Vivamus vitae lobortis mauris, eget tincidunt enim. Donec bibendum, erat vel tincidunt vehicula, ipsum nisl blandit nunc, malesuada laoreet neque sapien eget urna. Donec dapibus, metus eu ultrices consectetur, ipsum est pretium neque, ut sollicitudin lorem quam et neque. Suspendisse ultrices mauris quis erat luctus tristique. Morbi imperdiet, ipsum a bibendum laoreet, nibh leo lacinia mauris, non commodo nisl massa consequat nunc. Proin sollicitudin dictum hendrerit.</p>
                <div class="close">X</div>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="boxed">
          		<div class="head">
                	<span>CO</span>
                    <a href="#"><h3>Junior Graphic Designer - Full Time</h3></a>
                    <p>CompAndSsave.com-CA Team | Newark, CA</p>
                </div>
                <p>orem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ut luctus urna, eget cursus sapien. Vivamus vitae lobortis mauris, eget tincidunt enim. Donec bibendum, erat vel tincidunt vehicula, ipsum nisl blandit nunc, malesuada laoreet neque sapien eget urna. Donec dapibus, metus eu ultrices consectetur, ipsum est pretium neque, ut sollicitudin lorem quam et neque. Suspendisse ultrices mauris quis erat luctus tristique. Morbi imperdiet, ipsum a bibendum laoreet, nibh leo lacinia mauris, non commodo nisl massa consequat nunc. Proin sollicitudin dictum hendrerit.</p>
                <span class="newJob">new</span>
                <div class="close">X</div>
          </div>
        </div>
      </div>
      <div class="row joblist">
        <div class="col-sm-6">
          <div class="boxed">
          		<div class="head">
                	<span>CO</span>
                    <a href="#"><h3>Junior Graphic Designer - Full Time</h3></a>
                    <p>CompAndSsave.com-CA Team | Newark, CA</p>
                </div>
                <p>orem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ut luctus urna, eget cursus sapien. Vivamus vitae lobortis mauris, eget tincidunt enim. Donec bibendum, erat vel tincidunt vehicula, ipsum nisl blandit nunc, malesuada laoreet neque sapien eget urna. Donec dapibus, metus eu ultrices consectetur, ipsum est pretium neque, ut sollicitudin lorem quam et neque. Suspendisse ultrices mauris quis erat luctus tristique. Morbi imperdiet, ipsum a bibendum laoreet, nibh leo lacinia mauris, non commodo nisl massa consequat nunc. Proin sollicitudin dictum hendrerit.</p>
                <span class="newJob">new</span>
                <div class="close">X</div>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="boxed">
          		<div class="head">
                	<span>CO</span>
                    <a href="#"><h3>Junior Graphic Designer - Full Time</h3></a>
                    <p>CompAndSsave.com-CA Team | Newark, CA</p>
                </div>
                <p>orem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ut luctus urna, eget cursus sapien. Vivamus vitae lobortis mauris, eget tincidunt enim. Donec bibendum, erat vel tincidunt vehicula, ipsum nisl blandit nunc, malesuada laoreet neque sapien eget urna. Donec dapibus, metus eu ultrices consectetur, ipsum est pretium neque, ut sollicitudin lorem quam et neque. Suspendisse ultrices mauris quis erat luctus tristique. Morbi imperdiet, ipsum a bibendum laoreet, nibh leo lacinia mauris, non commodo nisl massa consequat nunc. Proin sollicitudin dictum hendrerit.</p>
                <div class="close">X</div>
          </div>
        </div>
      </div>
    </div>
    </div>