 <div class="center forgot bordered" ng-app="ResetApp" ng-controller="ResetController"> 
      <h1>Forgot Password</h1>
      <div ng-if="emailSent!=null">
		<div class="alert alert-success">
		  <strong>Please check your email!</strong>
		</div>
	</div>
      <div class="row m40">
      	<div class="col-sm-offset-1 col-sm-10">
        <form class="form-horizontal" id="forgot" name="resetForm" ng-submit="submitForm()" novalidate>
            <div class="form-group">
                <p>Forgot your password? Enter your username and we will send a email to reset your password.</p>
            </div>
                <div id="message-box" ng-if="resetError!=null" class="alert alert-danger has-error">
				  <div class="message-content"> {{ resetError }}</div>
				</div>
             <div class="form-group"
                     ng-class="{ 'has-error' : resetForm.email.$invalid && !resetForm.email.$pristine }">
                    <input type="email" class="input-sm form-control" placeholder="Your email address"
                           ng-model="resetForm.email" required/>

                    <p ng-show="resetForm.email.$invalid && !resetForm.email.$pristine" class="help-block">Enter a valid
                        email.</p>
                </div>
          <div class="form-group">
              <input type="submit" value="Submit" class="btn btn-primary btn-block" ng-disabled="resetForm.$invalid"/>
          </div>
        </form>
        </div>
      </div>
    </div>
    <script>
    var app = angular.module('ResetApp', []);
    app.controller('ResetController', function ($scope, $http) {
        $scope.submitForm = function () {
            if ($scope.resetForm.$valid) {
                var form ={
                  "email": $scope.resetForm.email
                };
                $http.post('/api/forgot-password', form).success(function (response) {
                    if (response.status == "Successful") {
                    	$scope.emailSent = true;
                       // window.location = "/";
                    } else {
                        $scope.resetError = response.message;
                    }
                });
            }

        };

    });

</script>