    <div class="center home-search-container">
      <h1>Change Your</h1>
      <h2 class="blue">Strategy</h2>
      <p>Search Smart  |  Search Quick  |  Search Now</p>
      <div class="row m40">
        <form class="form-horizontal" id="findJob" action="/search" method="GET">
          <div class="form-group">
            <div class="col-sm-6">
              <input type="text" name="term" class="input-sm form-control" placeholder="Job Title/Keyword" />
            </div>
            <div class="col-sm-6">
              <input type="text" name="location" class="input-sm form-control" placeholder="Location (City, State, Zip)"/>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-12">
              <input type="submit" value="Find Job" class="btn btn-primary btn-block" />
            </div>
          </div>
        </form>
      </div>
    </div>